"""Auto-commit + push + open-PR helper for the v6 ticket runner.

Lives separate from ``adk_runner`` so the orchestrator stays focused on
ticket lifecycle. Two public entry points:

* :func:`run_git`              — thin subprocess wrapper (5-min cap).
* :func:`commit_push_open_pr`  — full happy/sad path for the runner.

The PR step short-circuits cleanly when:

* the workspace isn't a git repo
* the working tree has no Doer-authored changes (transient cache dirs
  excluded — see ``_EXCLUDE_PATHSPECS``)
* ``gh`` CLI isn't installed (push still happens, PR step is skipped
  with a logged hint)

Returns a metadata patch dict the runner merges into ticket metadata
so the human triage loop sees ``pr_url``, ``branch_pushed``, and
``pr_skip_reason`` together.
"""
from __future__ import annotations

import logging
import os
import shutil
import subprocess


log = logging.getLogger("aiforge.git_pr")


# Transient dirs the runner / sidecars write into the workspace. Must
# NOT land in PRs even when the target repo's own .gitignore doesn't
# cover them (most don't — graphify-out came in via the AIForgeCrew
# convention, not the target repo's). Used at status + add time so
# the diff stays scoped to real Doer work.
_EXCLUDE_PATHSPECS: tuple[str, ...] = (
    ":(exclude)graphify-out",
    ":(exclude).aiforge",
    ":(exclude).aiforge-worktrees",
    ":(exclude).idea",
    ":(exclude).vscode",
    ":(exclude).DS_Store",
)


def run_git(args: list[str], cwd: str) -> tuple[int, str, str]:
    """Run a git/gh command and capture stdout/stderr.

    Returns ``(returncode, stdout[:1000], stderr[:1000])``. Hard 5-min
    timeout per call so a hung remote can't stall the runner.
    """
    proc = subprocess.run(
        args, cwd=cwd, capture_output=True, text=True, timeout=300,
    )
    return proc.returncode, (proc.stdout or "")[:1000], (proc.stderr or "")[:1000]


def _resolve_repo_root() -> str | None:
    """Honour ``AIFORGE_REPO_ROOT`` and confirm it's a git repo."""
    repo_root = os.path.expanduser(os.environ.get(
        "AIFORGE_REPO_ROOT", "~/aiforge_workspace",
    ))
    if not os.path.isdir(os.path.join(repo_root, ".git")):
        log.warning("git_pr.skip: %s is not a git repo", repo_root)
        return None
    return repo_root


def _has_doer_changes(repo_root: str) -> tuple[bool, str]:
    """``(True, "")`` when there's at least one tracked-or-untracked
    change OUTSIDE the transient-dir allowlist. ``(False, reason)``
    otherwise so the caller can return early with ``pr_skip_reason``."""
    rc, out, err = run_git(
        ["git", "status", "--porcelain", "--", ".", *_EXCLUDE_PATHSPECS],
        repo_root,
    )
    if rc != 0:
        log.warning("git_pr.status_failed: %s", err)
        return False, "git_status_failed"
    if not out.strip():
        log.info("git_pr.clean: no Doer changes (transient dirs excluded)")
        return False, "no_changes"
    return True, ""


def _checkout_branch(repo_root: str, branch: str) -> str:
    """Create the ticket branch from current HEAD. Returns ``""`` on
    success or a ``pr_skip_reason`` string on failure."""
    run_git(["git", "branch", "-D", branch], repo_root)  # ignore rc
    rc, _, err = run_git(["git", "checkout", "-b", branch], repo_root)
    if rc != 0:
        log.warning("git_pr.checkout_failed: %s", err)
        return "checkout_failed"
    return ""


def _commit_changes(repo_root: str, identifier: str, title: str) -> str:
    """Stage Doer changes (transient dirs excluded) and commit. Returns
    ``""`` on success or a ``pr_skip_reason`` on failure."""
    run_git(
        ["git", "add", "--", ".", *_EXCLUDE_PATHSPECS],
        repo_root,
    )
    msg = (
        f"feat({identifier}): {title}\n\n"
        f"Generated by AIForgeCrew v6 pipeline."
    )
    rc, out, err = run_git(["git", "commit", "-m", msg], repo_root)
    if rc != 0 and "nothing to commit" not in (out + err):
        log.warning("git_pr.commit_failed: %s", err)
        return "commit_failed"
    return ""


def _push(repo_root: str, branch: str) -> tuple[bool, str]:
    """``(pushed?, err_or_empty)``."""
    rc, _, err = run_git(
        ["git", "push", "-u", "origin", branch], repo_root,
    )
    if rc != 0:
        log.warning("git_pr.push_failed: %s", err)
        return False, err[:300]
    return True, ""


def _open_pr(repo_root: str, identifier: str, title: str,
             body: str) -> tuple[str, str]:
    """``(pr_url, error_or_empty)``. PR url is empty when ``gh`` is
    absent — push has already happened by then."""
    if not shutil.which("gh"):
        log.info("git_pr.gh_absent — push done, skipping PR creation")
        return "", "gh_not_installed"
    rc, out, err = run_git(
        ["gh", "pr", "create",
         "--title", f"{identifier}: {title}",
         "--body", body],
        repo_root,
    )
    if rc != 0:
        log.warning("git_pr.gh_create_failed: %s", err)
        return "", err[:300]
    pr_url = (out or "").strip().splitlines()[-1] if out else ""
    log.info("git_pr.opened: %s", pr_url)
    return pr_url, ""


def commit_push_open_pr(ticket) -> dict:
    """Commit Doer edits, push to origin, open a PR via ``gh`` CLI.

    Returns a metadata patch dict the caller merges into ticket
    metadata. Possible keys: ``pr_url``, ``branch_pushed``,
    ``pr_skip_reason``, ``push_err``, ``gh_err``. Empty dict on hard
    failure (caller still records the ticket as blocked).
    """
    repo_root = _resolve_repo_root()
    if repo_root is None:
        return {"pr_skip_reason": "not_a_git_repo"}

    has_changes, reason = _has_doer_changes(repo_root)
    if not has_changes:
        return {"pr_skip_reason": reason}

    branch = ticket.branch or f"aiforge/{ticket.identifier}"
    err = _checkout_branch(repo_root, branch)
    if err:
        return {"pr_skip_reason": err}

    title = (ticket.title or ticket.identifier).strip().replace("\n", " ")
    err = _commit_changes(repo_root, ticket.identifier, title)
    if err:
        return {"pr_skip_reason": err}

    pushed, push_err = _push(repo_root, branch)
    if not pushed:
        return {"branch_pushed": False, "pr_skip_reason": "push_failed",
                "push_err": push_err}

    pr_body = (
        f"AIForgeCrew v6 pipeline auto-generated PR for ticket "
        f"{ticket.identifier}.\n\n"
        f"## Original ticket body\n{(ticket.body or '')[:1500]}"
    )
    pr_url, pr_err = _open_pr(repo_root, ticket.identifier, title, pr_body)
    if not pr_url:
        return {"branch_pushed": True,
                "pr_skip_reason": pr_err or "gh_create_failed",
                "gh_err": pr_err}
    return {"branch_pushed": True, "pr_url": pr_url}


__all__ = ["run_git", "commit_push_open_pr"]
