#!/usr/bin/env bash
# scripts/install-hermes-serial.sh — install a flock wrapper around the hermes
# CLI so only ONE agent can run at a time across the whole Mac Studio.
#
# Paperclip's heartbeat scheduler enqueues multiple agents per tick. With 3
# local MoE models + Hindsight daemon + LM Studio overhead, running 2+
# hermes sessions concurrently blows through RAM (observed 37 GB swap in
# the first run). Parallel runs also made "small" models hallucinate
# completion instead of actually executing tools.
#
# This wrapper acquires a shared flock on /tmp/aiforge-hermes.lock. Second
# concurrent invocation blocks until the first exits. No timeouts, no retry
# logic — Paperclip's 900s per-run timeout provides the ceiling.
#
# Installs /Users/<you>/.local/bin/hermes-serial + wires it into all 3
# hermes_local agents (qa/engineer/cto) via adapter_config.hermesCommand.
#
# Idempotent.
set -euo pipefail

[[ "$(uname -s)" == "Darwin" ]] || { echo "hermes-serial: macOS only" >&2; exit 1; }

BIN="$HOME/.local/bin/hermes-serial"
HERMES="${HERMES:-$HOME/.local/bin/hermes}"
LOCK="${LOCK:-/tmp/aiforge-hermes.lock}"
FLOCK="${FLOCK:-/opt/homebrew/bin/flock}"

[[ -x "$HERMES" ]] || { echo "hermes CLI missing at $HERMES" >&2; exit 1; }

# macOS has no flock binary — install via brew.
if [[ ! -x "$FLOCK" ]]; then
  if command -v brew >/dev/null; then
    echo ">>> installing flock via brew"
    brew install flock 2>&1 | tail -3
  else
    eval "$(/opt/homebrew/bin/brew shellenv)" 2>/dev/null || true
    brew install flock 2>&1 | tail -3
  fi
fi
[[ -x "$FLOCK" ]] || { echo "flock still missing at $FLOCK after brew install — abort" >&2; exit 1; }

mkdir -p "$HOME/.local/bin"
cat > "$BIN" <<EOF
#!/usr/bin/env bash
# Serial wrapper — only one hermes agent session at a time.
# Generated by scripts/install-hermes-serial.sh. Do not edit by hand.
#
# Absolute path to flock because Paperclip spawns this as subprocess with
# minimal PATH — /opt/homebrew/bin is not necessarily on it.
exec "$FLOCK" -x "$LOCK" "$HERMES" "\$@"
EOF
chmod +x "$BIN"
echo "wrote $BIN (wraps $HERMES via $FLOCK, lock=$LOCK)"

# Wire into Paperclip — set adapter_config.hermesCommand for all hermes_local agents.
PG="$HOME/.pg0/installation/18.1.0/bin/psql"
if [[ -x "$PG" ]]; then
  PGPASSWORD=paperclip "$PG" -h 127.0.0.1 -p 54329 -U paperclip -d paperclip <<SQL
UPDATE agents
  SET adapter_config = jsonb_set(adapter_config, '{hermesCommand}', '"$BIN"'::jsonb)
  WHERE adapter_type = 'hermes_local';
SELECT role, adapter_config->>'hermesCommand' AS cmd FROM agents WHERE adapter_type = 'hermes_local' ORDER BY role;
SQL
else
  echo "WARN: psql not found — skipping Paperclip DB wire-up. Set adapter_config.hermesCommand='$BIN' manually."
fi

echo
echo "Restart Paperclip so it picks up the new hermesCommand:"
echo "  launchctl kickstart -k gui/\$(id -u)/com.aiforge.paperclip"
